on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_603b05a5_9916_4f55_8bc3_e4a3fac53407_API_KEY }}
          config_path_input: 'openfn-603b05a5-9916-4f55-8bc3-e4a3fac53407-config.json'
